select R.DOCCOD,
       R.DOCRECITM AS ITEM,R.DOCRECTPO AS TIPO,
       R.DOCRECSER AS SERIE,R.DOCRECNRO AS COMPROBANTE, R.DOCRECMNT AS MONTO,
       R.DOCRECFPAG AS FECHA,
       R.DOCRECFACT        
from tdddoc06 R, TDDDOC01 D
where R.DOCCOD = D.DOCCOD AND 
      D.TPODOCCOD = 'EXPE' AND
      D.DOCANONUM = 2012 AND
      D.DOCCOR = 50