Select S.DOCCOD,
       S.SEGCOD AS ITM , S.SEGFCH AS FECHA , S.SEGHRA AS HORA ,
       T.TARDSC AS TAREA , E.STSDSC AS ESTADO ,
       CONCAT(U1.UNIORGSIG, '-', C1.CARDSC, '-', T1.TRBAPENOM) UO_ORIGEN,
       CONCAT(U2.UNIORGSIG, '-', C2.CARDSC, '-', T2.TRBAPENOM) UO_DESTINO,
       CONCAT(R.USRAPEPAT,R.USRAPEMAT,R.USRNOM) USUARIO,
       S.SEGGLO AS GLOSA_SEGUIMIENTO
from TDDDOC02 s, tdbtar01 T , TDBEST01 E , rhduor01 U1 , rhduor01 U2 , rhbcar01 C1 ,
     rhbcar01 C2 , rhdtrb01 T1 , rhdtrb01 T2, NSBUSR01 R , tdddoc01 d
where S.TARCOD = T.TARCOD AND S.SEGSTSCOD = E.STSCOD and S.SEGUOORICO = U1.uniorgcod
      and S.SEGUODESCO = U2.uniorgcod AND S.SEGCARORIC = C1.CARCOD  AND S.SEGCARDESC=C2.CARCOD
      and S.SEGEMPORIC = T1.TRBCOD AND S.SEGEMPDESC = T2.TRBCOD AND S.SEGUSR = R.USRCOD
      and S.DOCCOD=D.DOCCOD
      AND D.DOCANONUM = 2012
      AND D.DOCCOR = 50
      and D.TPODOCCOD = 'EXPE'

ORDER BY S.SEGCOD DESC